spin_manifest_version = 2

[application]
authors = ["Chris Anders <filmee24@gmail.com>"]
description = "test"
name = "dotnet-test"
version = "1.0.0"

[[trigger.http]]
route = "/..."
component = "dotnet-test"

[component.dotnet-test]
source = "bin/Release/net8.0/DotnetTest.wasm"
sqlite_databases = ["default"]
key_value_stores = ["default"]

[component.dotnet-test.build]
command = "dotnet build -c Release"

[[trigger.http]]
route = "/static/..."
component = "static"

[component.static]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.3.0/spin_static_fs.wasm", digest = "sha256:ef88708817e107bf49985c7cefe4dd1f199bf26f6727819183d5c996baa3d148" }
files = [{ source = "assets", destination = "/" }]