spin_manifest_version = 2

[application]
authors = ["Chris Anders <filmee24@gmail.com>"]
description = "test"
name = "dotnet-test"
version = "1.0.0"

[[trigger.http]]
route = "/..."
component = "dotnet-test"

[component.dotnet-test]
source = "bin/Release/net10.0/DotnetTest.wasm"
sqlite_databases = ["default"]
key_value_stores = ["default"]

[component.dotnet-test.build]
command = "dotnet build -c Release"